### PR TITLE
Frodo

### PR DESCRIPTION
**Pull request by kibergus**
Hello. I've finished some work on MFC decoder refactoring and would like to merge them. This pull request contains:
1) Some changes from upstream incorporated by vamanea. I've taken them from https://github.com/vamanea/xbmc
2) Support for XU through libhybris from vamanea.
3) A lot of MFC decoder refactoring. Now U2 and XU have many shared code and I beleive, that it should be much easier to develop it further.
4) Tis is a single branch for all odroid boards.
5) Fixes for correct dts handling. This especially affects some interlaced video, where fields are written in separate packets.
6) MFC input queue is beeing kept fully loaded. I believe that it helps to keep MFC busy all the time.
7) Some fixes to Makefiles for U2, you don't need to patch Makefile after ./configure script
8) Workaround for interlaced video XU bug. I believe, that android decoder is affected by this bug too.

Some notes: I've switched compiler to C++11 mode because of tasty features of C++11. All patches with MFC refactoring could be applied to gotham branch too.

### CODE REVIEW

**Comment by mihailescu2m** [comment]
Can this be compiled with gcc-4.6 ?

**Comment by kibergus** [comment]
No. But gcc-4.7 works fine. I think, that all distributions for odroid already have modern versions of gcc and it is not a big problem. It is not very hard to fix gcc-4.6 build, "--std=c++11" key should be changed to "--std=c++0x" and initializer lists should be replaced with constructor calls.
Is gcc-4.6 support a required?

**Comment by mihailescu2m** [comment]
gcc 4.6 still is the default on wheezy, where xbmc still works best currently. but gcc 4.7 can be installed, so it should be ok.

**Comment by mihailescu2m** [comment]
There are 2 issues, one major:

1) MFC on XU is very reliable, no need to use software. I haven't got ONE issue with MFC, and I've used it every day for months (at some point I had 2 months uptime, with no XBMC restart).
2) With the code refactoring, dts/pts does not work well anymore. Skipping ahead in a movie will lose sync of video, it becomes jerky and behind sound. I have tested this only on the XU. It's unusable.

**Comment by kibergus** [comment]
> 2) With the code refactoring, dts/pts does not work well anymore. Skipping ahead in a movie will lose sync of video, it becomes jerky and behind sound. I have tested this only on the XU. It's unusable.

Yes, I see it now. It starts after 35:50 on different videos, so it should be something like rounding error. I'll look at it.

> 1) MFC on XU is very reliable, no need to use software. I haven't got ONE issue with MFC, and I've used it every day for months (at some point I had 2 months uptime, with no XBMC restart).

I have one DVD disk, that can be software decoded, but is laggy with MFC. I have a slight suspection, that problem is again with pts'es, but it is a different problem. So I've decided to disable MFC for videos that can be software decoded and concentrate on HD videos.
I'll add special log entry, which would state, why MFC codec was not used. If you want, I can remove this intristic at all.

**Comment by kibergus** [comment]
I thought, that if time is stored as double, then it is in seconds. Comment in DVDVideoPicture states the same. But in reality it is in microseconds. So there was an overflow.

**Comment by mihailescu2m** [comment]
Can you push the fix?

**Comment by kibergus** [comment]
Yes. Here is pull request:
https://github.com/mdrjr/xbmc/pull/2

**Pull request merged**
